services:
  - type: web
    name: panel-seguimiento
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Portada:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
